In [1]:
import torch

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.ndim

0

In [6]:
type(scalar)

torch.Tensor

In [7]:
device = 'mps' if torch.mps.is_available() else 'cpu'

In [8]:
device

'mps'

In [9]:
random_tensor = torch.rand(size=[2, 3])

In [11]:
random_tensor.to(device)

tensor([[0.2542, 0.5438, 0.7519],
        [0.7640, 0.3368, 0.3735]], device='mps:0')

In [12]:
random_tensor.device

device(type='cpu')

In [14]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [15]:
tensor_A.shape

torch.Size([3, 2])

In [16]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)

In [18]:
output.shape

torch.Size([3, 6])

In [19]:
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [20]:
tensor_A.requires_grad

False

In [21]:
x = torch.arange(1., 8.)

In [22]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [23]:
x.dtype

torch.float32

In [24]:
x.shape

torch.Size([7])

In [25]:
x_reshape = x.reshape(1, 7)

In [26]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [27]:
x.reshape(2, 3)

RuntimeError: shape '[2, 3]' is invalid for input of size 7

In [32]:
x.shape

torch.Size([7])

In [31]:
torch.stack([x, x, x, x], dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [34]:
x.unsqueeze(dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [35]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [37]:
x[:, 0]

tensor([[1, 2, 3]])

In [44]:
torch.manual_seed(42)
a = torch.rand(size=(7, 7))
torch.manual_seed(42)
b = torch.rand(size=(1, 7))

In [40]:
a.shape

torch.Size([7, 7])

In [41]:
b.shape

torch.Size([1, 7])

In [43]:
ab = torch.matmul(a, b.T)

In [48]:
torch.mps.manual_seed(1234)
a = torch.rand(size=(2, 3), device=device)
torch.mps.manual_seed(1234)
b = torch.rand(size=(2, 3), device=device)

In [50]:
m = torch.matmul(a, b.T)

In [52]:
m

tensor([[1.4948, 0.9231],
        [0.9231, 1.0608]], device='mps:0')

In [51]:
m.max()

tensor(1.4948, device='mps:0')

In [53]:
m.min()

tensor(0.9231, device='mps:0')

In [54]:
m.argmin()

tensor(1, device='mps:0')

In [58]:
m[m.argmax()][m[m.argmax()].argmax()]

tensor(1.4948, device='mps:0')

In [60]:
torch.manual_seed(7)
n = torch.rand(size=(1, 1, 1, 10))

In [63]:
n.squeeze().shape

torch.Size([10])